import type { Metadata } from "next";
import { Inter, Space_Mono } from 'next/font/google';
import "@/app/globals.css";
import { Header } from "@/app/components/header";
import { Footer } from "@/app/components/footer";


const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter', // Defines the CSS variable name
})

const spaceMono = Space_Mono({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-space-mono', 
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: { 
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceMono.variable}`}>
      <body className="antialiased bg-[#111] text-white p-15 md:max-w-3xl lg:max-w-4xl  mx-auto">
        
        <div 
          className="noise fixed inset-0 pointer-events-none z-[9999]" 
          aria-hidden="true" 
        />

        <div className="relative z-10">  
          <Header />
            <main className="flex-grow">{children}</main>
          <Footer />
        </div>
        
      </body>
    </html>
  );
}