import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Header } from "@/app/components/header";
import { Footer } from "@/app/components/footer";
import { About } from "@/app/components/About";
import { Contact } from "@/app/components/Contact";
import { Skills } from "@/app/components/Skills";


const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="mx-auto bg-background min-h-screen content-overlay max-w-xl">
          <Header />
          <About />
          <Skills />
          <Contact />
          <Footer />
        </div>
      </body>
    </html>
  );
}
